<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.25.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\Authentication\Logout\" />
    <Folder Include="Entities\Authentication\ChangePassword\" />
    <Folder Include="Entities\Authentication\RefreshToken\" />
  </ItemGroup>

</Project>
